/* Eksempeldata til eventlisten (events.js), fra kildeanalysen 6. oktober 2026 (teknisk/datakilder/13-events-kildeanalyse.md).
   Datoer og priser skal verificeres hos kilden. confirmed:false = traditionel dato (plejer at ligge her), ikke bekræftet. Gengenereres ikke automatisk. */
window.GL_EVENTS = [
 {
  "id": "afternoon-tea-admini",
  "title_da": "Afternoon tea på Rjukan Admini",
  "title_en": "Afternoon tea at Rjukan Admini",
  "start": "2026-10-10T00:00:00+02:00",
  "end": "2026-11-14T00:00:00+01:00",
  "allDay": true,
  "place": "Rjukan Admini Hotel, Sølvvoldveien 3, Rjukan",
  "category": "mad",
  "blurb_da": "Afternoon tea på lørdage på det historiske hotel (10., 17., 24., 31. okt og 7., 14. nov).",
  "price": null,
  "url": "https://visitrjukan.com/en/p/afternoon-tea-pa-rjukan-admini/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "agitato-hostkonsert-2026",
  "title_da": "Høstkonsert med Agitato",
  "title_en": "Autumn concert with Agitato",
  "start": "2026-10-16T00:00:00+02:00",
  "end": "2026-10-17T00:00:00+02:00",
  "allDay": true,
  "place": "Kinosalen, Rjukan",
  "category": "musik",
  "blurb_da": "Lokalt kor holder høstkonsert i Rjukan.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/hostkonsert-med-agitato/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "yoga-retreat-gaustablikk-2026",
  "title_da": "Yoga retreat på Gaustablikk Fjellresort",
  "title_en": "Yoga retreat at Gaustablikk Fjellresort",
  "start": "2026-10-23T00:00:00+02:00",
  "end": "2026-10-25T00:00:00+02:00",
  "allDay": true,
  "place": "Gaustablikk Fjellresort (Heddersrom)",
  "category": "sport",
  "blurb_da": "Weekend med yoga, lydbad og ro i fjeldet sammen med Wanderlust Yoga, maks 20 deltagere.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/yoga-retreat-pa-gaustablikk-fjellresort/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "granlund-intimkonsert-2026",
  "title_da": "Trond Granlund: intimkonsert og middag",
  "title_en": "Trond Granlund: intimate concert and dinner",
  "start": "2026-10-24T00:00:00+02:00",
  "end": null,
  "allDay": true,
  "place": "Rjukan Admini Hotel",
  "category": "musik",
  "blurb_da": "Koncert kombineret med middag på hotellet.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/trond-granlund-intimkonsert-og-middag/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "damenes-aften-2026",
  "title_da": "Damenes Aften på Rjukan",
  "title_en": "Ladies' Night in Rjukan",
  "start": "2026-10-30T18:00:00+01:00",
  "end": null,
  "allDay": false,
  "place": "Rjukan sentrum",
  "category": "kultur",
  "blurb_da": "Aftenåbent i centrum med Crazy Bingo Show og gratis vafler, traditionelt sidste fredag i oktober.",
  "price": "Gratis vafler (entré ikke oplyst)",
  "url": "https://www.visittelemark.no/arrangementer/damenes-aften-pa-rjukan",
  "confirmed": true,
  "source": "Visit Telemark (visittelemark.no)",
  "recurring": "Sidste fredag i oktober (kildepåstand)"
 },
 {
  "id": "lutefisk-admini-2026",
  "title_da": "Lutefiskaften med Jørn Hoel (middag og minikoncert)",
  "title_en": "Lutefisk evening with Jørn Hoel (dinner and mini concert)",
  "start": "2026-11-05T00:00:00+01:00",
  "end": null,
  "allDay": true,
  "place": "Rjukan Admini Hotel",
  "category": "mad",
  "blurb_da": "Lutefiskmiddag med minikoncert.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/lutefiskaften-med-jorn-hoel-middag-minikonsert/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "rakfisk-austbygde-2026",
  "title_da": "Rakfiskaften på Austbygde bakeri",
  "title_en": "Rakfisk evening at Austbygde bakery",
  "start": "2026-11-07T00:00:00+01:00",
  "end": null,
  "allDay": true,
  "place": "Austbygde bakeri, Mogan 2, Tinn Austbygd",
  "category": "mad",
  "blurb_da": "Fermenteret ørred fra Tinn serveret som aftenarrangement.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/rakfiskaften-pa-austbygde-bakeri/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "rakfisk-rjukan-hotell-2026",
  "title_da": "Rakfiskaften på Rjukan Hotell",
  "title_en": "Rakfisk evening at Rjukan Hotell",
  "start": "2026-11-13T18:00:00+01:00",
  "end": null,
  "allDay": false,
  "place": "Rjukan Hotell, restaurant D2O",
  "category": "mad",
  "blurb_da": "Rakfisk fra Tinn med lefse og tilbehør i hotellets restaurant.",
  "price": "NOK 365 pr. tallerken",
  "url": "https://visitrjukan.com/en/p/rakfiskaften-pa-rjukan-hotell/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "julebord-skotten-2026",
  "title_da": "Julebord med The Skotten Show",
  "title_en": "Christmas party with The Skotten Show",
  "start": "2026-11-20T00:00:00+01:00",
  "end": null,
  "allDay": true,
  "place": "Den Lykkelige Sportsmann, Kvitåvatnvegen 461",
  "category": "musik",
  "blurb_da": "Julebord med show på Gausta.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/julebord-med-the-skotten-show/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "gaustablikk-julebord-2026",
  "title_da": "Julebord på Gaustablikk Fjellresort (fredage og lørdage)",
  "title_en": "Christmas dinners at Gaustablikk Fjellresort (Fri and Sat)",
  "start": "2026-11-20T00:00:00+01:00",
  "end": "2026-12-12T00:00:00+01:00",
  "allDay": true,
  "place": "Gaustablikk Fjellresort",
  "category": "mad",
  "blurb_da": "Julebordsaftener på fredage og lørdage fra 20. nov til 12. dec.",
  "price": null,
  "url": "https://www.gausta.com/jul-og-nyttar/",
  "confirmed": true,
  "source": "Gausta (gausta.com)",
  "recurring": null
 },
 {
  "id": "lutefisk-rjukan-hotell-2026",
  "title_da": "Lutefiskaften på Rjukan Hotell",
  "title_en": "Lutefisk evening at Rjukan Hotell",
  "start": "2026-11-21T00:00:00+01:00",
  "end": null,
  "allDay": true,
  "place": "Rjukan Hotell, restaurant D2O",
  "category": "mad",
  "blurb_da": "Lutefisk med bacon, ærtepuré og mandelkartofler.",
  "price": "NOK 495 pr. person",
  "url": "https://visitrjukan.com/en/p/lutefiskaften-pa-rjukan-hotell/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "atle-pettersen-julelys-2026",
  "title_da": "Atle Pettersen: Tusen julelys",
  "title_en": "Atle Pettersen: Thousand Christmas lights",
  "start": "2026-11-25T00:00:00+01:00",
  "end": null,
  "allDay": true,
  "place": "Rjukan kirke",
  "category": "musik",
  "blurb_da": "Julekoncert i Rjukan kirke.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/atle-pettersen-christmas-concert-in-rjukan-church/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "vera-lynn-hyldest-2026",
  "title_da": "Vera Lynn: The Forces' Sweetheart",
  "title_en": "Vera Lynn: The Forces' Sweetheart",
  "start": "2026-11-26T00:00:00+01:00",
  "end": null,
  "allDay": true,
  "place": "Verdensteatret Rjukan, Storesalen",
  "category": "musik",
  "blurb_da": "Musikalsk hyldest til Vera Lynn.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/vera-lynn-the-forces-sweetheart/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "julegrantenning-rjukan-2026",
  "title_da": "Julegrantenning på Rjukan torg",
  "title_en": "Christmas tree lighting at Rjukan square",
  "start": "2026-11-28T00:00:00+01:00",
  "end": null,
  "allDay": true,
  "place": "Rjukan torg",
  "category": "familie",
  "blurb_da": "Byens juletræ tændes på torvet.",
  "price": "Gratis (ikke oplyst, antaget)",
  "url": "https://www.visittelemark.no/arrangementer/julegrantenning-pa-rjukan-torg",
  "confirmed": true,
  "source": "Visit Telemark (visittelemark.no)",
  "recurring": "Sidst i november (tradition)"
 },
 {
  "id": "gausta-saesonaabning-2026",
  "title_da": "Gausta Skisenter: forventet sæsonåbning",
  "title_en": "Gausta Ski Resort: expected season opening",
  "start": "2026-11-28T00:00:00+01:00",
  "end": null,
  "allDay": true,
  "place": "Gausta Skisenter",
  "category": "ski",
  "blurb_da": "Skiinfo angiver forventet åbning 28. nov og regulær 11. dec, afhænger af sne og kulde.",
  "price": null,
  "url": "https://www.skiinfo.no/ostlandet/gaustablikk-gaustatoppen/skianlegg",
  "confirmed": false,
  "source": "Skiinfo.no (tredjepart, via websøgning)",
  "recurring": "Åbner ofte sent okt til dec afhængig af vejr"
 },
 {
  "id": "isklatring-rjukan-adventure-2026",
  "title_da": "Isklatring med Rjukan Adventure (sæson)",
  "title_en": "Ice climbing with Rjukan Adventure (season)",
  "start": "2026-12-07T00:00:00+01:00",
  "end": "2027-03-31T00:00:00+02:00",
  "allDay": true,
  "place": "Rjukan (kontor Skriugata 26)",
  "category": "sport",
  "blurb_da": "Guidede isklatrekurser fra begynder til videregået gennem hele vinteren.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/ice-climbing-with-rjukan-adventure/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": "Hver vinter"
 },
 {
  "id": "herborg-vemork-2026",
  "title_da": "Julekoncert med Herborg Kråkevik på Vemork",
  "title_en": "Christmas concert with Herborg Kråkevik at Vemork",
  "start": "2026-12-11T19:00:00+01:00",
  "end": null,
  "allDay": false,
  "place": "Maskinhallen, Vemork (Norsk Industriarbeidermuseum)",
  "category": "musik",
  "blurb_da": "Førjulsaften i den historiske maskinhal, indslip fra 19 og koncertstart senere på aftenen.",
  "price": "Koncertbillet NOK 690",
  "url": "https://visitrjukan.com/en/p/christmas-concert-with-herborg-krakevik-at-vemork/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "lyttesalong-mossing-2026",
  "title_da": "Lyttesalong med Randi Mossing",
  "title_en": "Listening salon with Randi Mossing",
  "start": "2026-12-13T00:00:00+01:00",
  "end": null,
  "allDay": true,
  "place": "Rjukan Admini Hotel",
  "category": "musik",
  "blurb_da": "Intim musikaften på hotellet.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/lyttesalong-med-randi-mossing/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "skitest-hotellbakken-2026",
  "title_da": "Ski Test i Hotellbakken",
  "title_en": "Ski test in Hotellbakken",
  "start": "2026-12-19T00:00:00+01:00",
  "end": "2027-03-20T00:00:00+01:00",
  "allDay": true,
  "place": "Hotellbakken, Gausta",
  "category": "ski",
  "blurb_da": "Gratis test af skibranchens nyheder med vejledning fra leverandører.",
  "price": "Gratis (ifølge Gausta)",
  "url": "https://www.gausta.com/aktivitetskalender/",
  "confirmed": true,
  "source": "Gausta (gausta.com)",
  "recurring": null
 },
 {
  "id": "jul-nytaar-gausta-2026",
  "title_da": "Jul og nytår på Gausta (Huski og Flaks, aktiviteter)",
  "title_en": "Christmas and New Year at Gausta",
  "start": "2026-12-23T00:00:00+01:00",
  "end": null,
  "allDay": true,
  "place": "Gausta",
  "category": "familie",
  "blurb_da": "Juleprogram med skiløb, børneaktiviteter og hyggelige måltider, løbende opdateret.",
  "price": null,
  "url": "https://www.gausta.com/jul-og-nyttar/",
  "confirmed": false,
  "source": "Gausta (gausta.com)",
  "recurring": "Hvert år, præcise datoer ikke verificeret"
 },
 {
  "id": "after-ski-yoga-gausta-2027",
  "title_da": "After Ski Gentle Yoga Stretch",
  "title_en": "After Ski Gentle Yoga Stretch",
  "start": "2027-01-05T00:00:00+01:00",
  "end": "2027-03-30T00:00:00+02:00",
  "allDay": true,
  "place": "Gausta",
  "category": "sport",
  "blurb_da": "Rolig yogatime for trætte ski- og fjeldkroppe.",
  "price": null,
  "url": "https://www.gausta.com/aktivitetskalender/",
  "confirmed": true,
  "source": "Gausta (gausta.com)",
  "recurring": "Hver vintersæson"
 },
 {
  "id": "hundekjoering-gausta-2027",
  "title_da": "Hundekørsel på Gausta",
  "title_en": "Dog sledding at Gausta",
  "start": "2027-01-07T00:00:00+01:00",
  "end": "2027-04-01T00:00:00+02:00",
  "allDay": true,
  "place": "Gausta",
  "category": "natur",
  "blurb_da": "Hundeslæde i naturen omkring Gausta.",
  "price": null,
  "url": "https://www.gausta.com/aktivitetskalender/",
  "confirmed": true,
  "source": "Gausta (gausta.com)",
  "recurring": "Hver vintersæson"
 },
 {
  "id": "fis-renn-gausta-2027",
  "title_da": "FIS-renn på Gausta",
  "title_en": "FIS race at Gausta",
  "start": "2027-01-07T00:00:00+01:00",
  "end": "2027-01-10T00:00:00+01:00",
  "allDay": true,
  "place": "Gausta Skisenter",
  "category": "ski",
  "blurb_da": "Slalom og storslalom på FIS-niveau.",
  "price": null,
  "url": "https://www.fis-ski.com/DB/general/event-details.html?sectorcode=AL&eventid=64320&seasoncode=2027",
  "confirmed": true,
  "source": "Gausta (gausta.com)",
  "recurring": null
 },
 {
  "id": "gaustablikkrennet-2027",
  "title_da": "Gaustablikkrennet 2027",
  "title_en": "Gaustablikkrennet 2027",
  "start": "2027-01-23T00:00:00+01:00",
  "end": "2027-01-24T00:00:00+01:00",
  "allDay": true,
  "place": "Gausta Skisenter",
  "category": "ski",
  "blurb_da": "Alpint stævne i slalom og storslalom arrangeret af Rjukan IL Alpint.",
  "price": null,
  "url": "https://isonen.no/event/cmp3wlpr302evce01w70w960z/gaustablikkrennet-sl-og-ssl/",
  "confirmed": true,
  "source": "Gausta (gausta.com)",
  "recurring": "Hvert år i januar (antaget)"
 },
 {
  "id": "norrona-ice-festival-2027",
  "title_da": "Norrøna Ice Festival 2027",
  "title_en": "Norrøna Ice Festival 2027",
  "start": "2027-02-11T00:00:00+01:00",
  "end": "2027-02-14T00:00:00+01:00",
  "allDay": true,
  "place": "Rjukan og Norrøna House, Oslo",
  "category": "festival",
  "blurb_da": "Firedages isklatrefestival med kurser, produkttest og foredrag sammen med Petzl.",
  "price": "Pris ikke verificeret",
  "url": "https://visitrjukan.com/en/p/norrona-ice-festival-2027/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": null
 },
 {
  "id": "vinterferie-uge8-2027",
  "title_da": "Vinterferie (norsk skoleferie, uge 8)",
  "title_en": "Winter holiday (Norwegian school break, week 8)",
  "start": "2027-02-22T00:00:00+01:00",
  "end": "2027-02-28T00:00:00+01:00",
  "allDay": true,
  "place": "Gausta",
  "category": "familie",
  "blurb_da": "Højsæson for norske familier med fuldt aktivitetsprogram på Gausta.",
  "price": null,
  "url": "https://www.gausta.com/vinterferie/",
  "confirmed": false,
  "source": "Gausta (gausta.com)",
  "recurring": "Uge 8 hvert år (Inference, skoleferiedatoer ikke verificeret)"
 },
 {
  "id": "super-g-helg-2027",
  "title_da": "Super-G-helg 2027",
  "title_en": "Super-G weekend 2027",
  "start": "2027-03-06T00:00:00+01:00",
  "end": "2027-03-07T00:00:00+01:00",
  "allDay": true,
  "place": "Gausta Skisenter",
  "category": "ski",
  "blurb_da": "Rjukan IL Alpint arrangerer Super-G-weekend.",
  "price": null,
  "url": "https://rjukanfotball.spond.club/alpint",
  "confirmed": true,
  "source": "Gausta (gausta.com)",
  "recurring": null
 },
 {
  "id": "paaske-gausta-2027",
  "title_da": "Påske på Gausta (påskeeggjagt m.m.)",
  "title_en": "Easter at Gausta (egg hunt etc.)",
  "start": "2027-03-25T00:00:00+01:00",
  "end": "2027-03-29T00:00:00+02:00",
  "allDay": true,
  "place": "Gausta",
  "category": "familie",
  "blurb_da": "Påskeferie med skiløb og børneaktiviteter, påskedag er 28. marts 2027.",
  "price": null,
  "url": "https://www.gausta.com/agenda/paskeeggjakt/",
  "confirmed": false,
  "source": "Gausta (gausta.com)",
  "recurring": "Hver påske, dato for programmet ikke verificeret"
 },
 {
  "id": "hovedlandsrennet-2027",
  "title_da": "Hovedlandsrennet alpint (HL27)",
  "title_en": "Norwegian Junior Alpine Championships (HL27)",
  "start": "2027-04-06T00:00:00+02:00",
  "end": "2027-04-11T00:00:00+02:00",
  "allDay": true,
  "place": "Gausta Skisenter",
  "category": "ski",
  "blurb_da": "Gausta er vært for et af Norges største alpintræf for ungdom.",
  "price": null,
  "url": "https://www.skiforbundet.no/arrangementer/hl-alpint/",
  "confirmed": true,
  "source": "Gausta (gausta.com)",
  "recurring": null
 },
 {
  "id": "solfesten-rjukan-2027",
  "title_da": "Solfesten på Rjukan",
  "title_en": "Sun Festival in Rjukan",
  "start": "2027-04-24T00:00:00+02:00",
  "end": null,
  "allDay": true,
  "place": "Rjukan by, Torget",
  "category": "festival",
  "blurb_da": "Byen fejrer solens tilbagekomst med optog, taler og kåringer, tradition siden 1925.",
  "price": null,
  "url": "https://www.visittelemark.no/arrangementer/solfesten-pa-rjukan",
  "confirmed": true,
  "source": "Visit Telemark og Visit Rjukan",
  "recurring": "Hvert forår, normalt omkring denne tid"
 },
 {
  "id": "1-mai-vemork-2027",
  "title_da": "1. maj på Vemork",
  "title_en": "1 May at Vemork",
  "start": "2027-05-01T00:00:00+02:00",
  "end": null,
  "allDay": true,
  "place": "Vemork (Norsk Industriarbeidermuseum)",
  "category": "kultur",
  "blurb_da": "Traditionel 1. maj-markering på museet, program ikke verificeret for 2027.",
  "price": null,
  "url": "https://www.nia.no/vemork/opplevelser/velkommen-til-1-mai-pa-vemork",
  "confirmed": false,
  "source": "NIA (nia.no)",
  "recurring": "Hvert år 1. maj (side set i sitemap, indhold ikke læst)"
 },
 {
  "id": "gausta-saesonslut-2027",
  "title_da": "Gausta Skisenter: forventet sæsonslut",
  "title_en": "Gausta Ski Resort: expected season end",
  "start": "2027-05-03T00:00:00+02:00",
  "end": null,
  "allDay": true,
  "place": "Gausta Skisenter",
  "category": "ski",
  "blurb_da": "Skiinfo angiver forventet lukning 3. maj 2027 (163 planlagte dage).",
  "price": null,
  "url": "https://www.skiinfo.no/ostlandet/gaustablikk-gaustatoppen/skianlegg",
  "confirmed": false,
  "source": "Skiinfo.no (tredjepart, via websøgning)",
  "recurring": "Typisk start maj"
 },
 {
  "id": "17-mai-gaustatoppen-2027",
  "title_da": "17. maj på Gaustatoppen",
  "title_en": "17 May on Gaustatoppen",
  "start": "2027-05-17T10:00:00+02:00",
  "end": null,
  "allDay": false,
  "place": "Gaustatoppen (Gaustabanen)",
  "category": "familie",
  "blurb_da": "Nationaldag med tog til toppen, taler kl. 14 og rømmegrøt på Turisthytta.",
  "price": "Almindelig billet til banen",
  "url": "https://gaustabanen.no/events/17-mai",
  "confirmed": false,
  "source": "Gaustabanen (gaustabanen.no)",
  "recurring": "Hvert år 17. maj, kl. 10-16 (2026-oplysninger)"
 },
 {
  "id": "luraasstemnet-2027",
  "title_da": "Luråsstemnet (folkemusik og dans)",
  "title_en": "Luråsstemnet (folk music and dance)",
  "start": "2027-06-04T00:00:00+02:00",
  "end": null,
  "allDay": true,
  "place": "Lurås, Tinn",
  "category": "musik",
  "blurb_da": "Traditionelt folkemusikstævne i Tinn, 2027-dato ikke verificeret.",
  "price": null,
  "url": "https://radiorjukan.no/aktuelt-lokalt/arrangementssommeren-i-tinn-2026/",
  "confirmed": false,
  "source": "Radio Rjukan (via websøgning)",
  "recurring": "Første weekend af juni (2026: 5.-7. juni)"
 },
 {
  "id": "marispelet-2027",
  "title_da": "Marispelet ved Rjukanfossen",
  "title_en": "Marispelet at Rjukanfossen",
  "start": "2027-07-10T00:00:00+02:00",
  "end": null,
  "allDay": true,
  "place": "Ved Vemork og Rjukanfossen",
  "category": "kultur",
  "blurb_da": "Udendørs historisk musikdrama ved vandfaldet.",
  "price": null,
  "url": "https://www.visittelemark.com/things-to-do/marispelet-rjukan-p6750303",
  "confirmed": false,
  "source": "Visit Telemark (via websøgning)",
  "recurring": "Plejer at køre i juli, 2027-datoer ukendte, startdato er skøn"
 },
 {
  "id": "norseman-2027",
  "title_da": "Norseman Xtreme Triathlon",
  "title_en": "Norseman Xtreme Triathlon",
  "start": "2027-07-31T00:00:00+02:00",
  "end": null,
  "allDay": true,
  "place": "Eidfjord til Gaustatoppen, mål ved Gausta",
  "category": "sport",
  "blurb_da": "Verdens hårdeste fuldlængde-triatlon slutter på Gaustatoppen, tilskuerpunkter i Austbygde og Gausta.",
  "price": null,
  "url": "https://visitrjukan.com/en/p/norseman-xtreme-triathlon/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": "Hvert år omkring 1. august"
 },
 {
  "id": "notodden-blues-2027",
  "title_da": "Notodden Blues Festival 2027",
  "title_en": "Notodden Blues Festival 2027",
  "start": "2027-08-05T00:00:00+02:00",
  "end": "2027-08-08T00:00:00+02:00",
  "allDay": true,
  "place": "Notodden (regional, ca. 1 times kørsel, ikke målt)",
  "category": "festival",
  "blurb_da": "Stor international blues festival, early bird-billetter sælges nu.",
  "price": "Se bluesfest.no/billetter",
  "url": "https://www.bluesfest.no/",
  "confirmed": true,
  "source": "Notodden Blues Festival",
  "recurring": "Hvert år ca. 1. weekend i august"
 },
 {
  "id": "gaustadagen-2027",
  "title_da": "Gaustadagen på Gaustatoppen",
  "title_en": "Gaustadagen on Gaustatoppen",
  "start": "2027-08-14T00:00:00+02:00",
  "end": null,
  "allDay": true,
  "place": "Gaustatoppen",
  "category": "kultur",
  "blurb_da": "Dag med musik og formidling på toppen, 'en dag i august', program og dato offentliggøres senere.",
  "price": null,
  "url": "https://gaustabanen.no/events/gaustadagen",
  "confirmed": false,
  "source": "Gaustabanen (gaustabanen.no)",
  "recurring": "En dag i august, dato ukendt, startdato er skøn"
 },
 {
  "id": "sveiven-2027",
  "title_da": "Sveiven 2027 (25 år)",
  "title_en": "Sveiven 2027 (25th edition)",
  "start": "2027-09-04T00:00:00+02:00",
  "end": null,
  "allDay": true,
  "place": "Gausta",
  "category": "natur",
  "blurb_da": "Social fjeldmarch for kvinder med AfterHike og musik, busser fra Rjukan.",
  "price": "Billet via Sveivens side",
  "url": "https://visitrjukan.com/en/p/sveiven-2027/",
  "confirmed": true,
  "source": "Visit Rjukan (visitrjukan.com)",
  "recurring": "Første weekend i september"
 },
 {
  "id": "hostmesse-gausta-2027",
  "title_da": "Høstmesse på Gausta",
  "title_en": "Autumn fair at Gausta",
  "start": "2027-10-02T00:00:00+02:00",
  "end": null,
  "allDay": true,
  "place": "Stova, Gaustablikk Fjellresort",
  "category": "familie",
  "blurb_da": "Lokale udstillere fra hele Tinn, tilbud og aktiviteter. 2026-udgaven var 3. okt kl. 11-15.",
  "price": "Gratis (antaget)",
  "url": "https://www.gausta.com/agenda/aktivitetskalender/",
  "confirmed": false,
  "source": "Gausta (gausta.com)",
  "recurring": "Første lørdag i oktober (2026-mønster), 2027-dato er skøn"
 },
 {
  "id": "damenes-aften-2027",
  "title_da": "Damenes Aften på Rjukan",
  "title_en": "Ladies' Night in Rjukan",
  "start": "2027-10-29T18:00:00+02:00",
  "end": null,
  "allDay": false,
  "place": "Rjukan sentrum",
  "category": "kultur",
  "blurb_da": "Årlig aftenåbent med underholdning, sidste fredag i oktober er 29. okt 2027.",
  "price": null,
  "url": "https://www.visittelemark.no/arrangementer/damenes-aften-pa-rjukan",
  "confirmed": false,
  "source": "Visit Telemark (visittelemark.no)",
  "recurring": "Sidste fredag i oktober (kildepåstand), 2027 beregnet"
 }
];
